definitions:
  handlers.Error:
    properties:
      error:
        type: string
      status:
        type: integer
    type: object
  tweet.Request:
    properties:
      data:
        type: string
    type: object
  tweet.Tweet:
    properties:
      data:
        type: string
      id:
        type: string
      timeStamp:
        type: string
      userID:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Endpoints for challenge Uala about mini twitter.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Challenge Uala
  version: "1.0"
paths:
  /v1/follow/{userIDToFollow}:
    post:
      consumes:
        - application/json
      description: Create a tweet from user
      parameters:
        - description: x-user-id
          in: header
          name: x-user-id
          required: true
          type: string
        - description: User ID
          in: path
          name: userIDToFollow
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.Error'
      summary: Create a tweet
  /v1/tweet:
    post:
      consumes:
        - application/json
      description: Follow an existent user for visualize the tweets
      parameters:
        - description: x-user-id
          in: header
          name: x-user-id
          required: true
          type: string
        - description: query params
          in: body
          name: request
          required: true
          schema:
            $ref: '#/definitions/tweet.Request'
      produces:
        - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.Error'
      summary: Follow a user
  /v1/viewline:
    get:
      consumes:
        - application/json
      description: View tweets of followers
      parameters:
        - description: x-user-id
          in: header
          name: x-user-id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/tweet.Tweet'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.Error'
      summary: View timeline of a user
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
